# Generated by Django 2.0.1 on 2018-01-23 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kenkoapp', '0003_auto_20180122_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('short_desc', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='care_img/')),
                ('price', models.IntegerField(default=15)),
                ('carepro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenkoapp.Carepro')),
            ],
        ),
    ]
