# Generated by Django 2.0.1 on 2018-01-24 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kenkoapp', '0004_care'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('number', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('avatar', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('total', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Ready'), (2, 'On the way'), (3, 'Arrived')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('caregiver', models.ForeignKey(on_delete='on_delete', to='kenkoapp.Caregiver')),
                ('carepro', models.ForeignKey(on_delete='on_delete', to='kenkoapp.Carepro')),
                ('customer', models.ForeignKey(on_delete='on_delete', to='kenkoapp.Customer')),
            ],
        ),
        migrations.AlterField(
            model_name='care',
            name='price',
            field=models.IntegerField(default=20),
        ),
    ]
